### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Julianezequieldev** [MathiasMC/BattleDrones#2]
I gave myself the administrator permissions, and even so the commands don't work, they only work if I'm op .. paper 1.16.3

**Comment by MathiasMC** [comment]
Sorry for late reply but i'm not checking github issues that often
mostly spigot

Have you got the battledrones permission? that is the main permission without it no access to any command

**Comment by SwadowMaster** [comment]
Hello tomattito dile a tu compa que queremos el reembolso Gracias un beso en el siempre sucio
