### ISSUE TITLE
NPE 

### ISSUE THREAD

**Issue by TheKlimoT** [MathiasMC/BattleDrones#4]
https://hastebin.com/nirisemotu.sql

1.3.2 version
Yatopia - 1.16.3
WG - WE LAST

**Comment by TheKlimoT** [comment]
![изображение](https://user-images.githubusercontent.com/26817853/98396779-52f24580-206f-11eb-86e9-f92f3cdeb457.png)
This, lagged drone, not deleting, and not attacking

**Comment by MathiasMC** [comment]
Sorry for late reply but i'm not checking github issues that often
mostly spigot

I will try solve this issue in the next version
